org.gradle.java.home=C:/Program Files/Microsoft/jdk-21.0.8.9-hotspot
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

kotlin.code.style=official
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx3072m -XX:+UseParallelGC

ksp.incremental=true
